# pull official base image
FROM node:12

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json package-lock.json* yarn.lock* ./
RUN yarn install && yarn cache clean

# add app
COPY . .

EXPOSE 3000

CMD ["yarn", "start"]